import { PALETTE } from '@/engine/config/Palette';

export const COLORS = {
  GREEN: PALETTE.GREEN.PRIMARY,
  YELLOW: PALETTE.YELLOW.SOFT,
  RED: PALETTE.RED.CRITICAL,
  PURPLE: PALETTE.PURPLE.PRIMARY,
  BLACK: PALETTE.MONO.BLACK,
  WHITE: PALETTE.MONO.WHITE,
};

export const BOOT_KEYS: Record<string, string> = {
    "INITIALIZE NEURAL_LACE": "INIT",
    "CONNECTED TO LATENT_SPACE": "LINK",
    "MOUNT MESOELFY_CORE": "MOUNT",
    "UNSAFE CONNECTION DETECTED": "UNSAFE",
    "BYPASSING SENTINEL_NODES": "BYPASS",
    "DECRYPTED": "DECRYPTED",
    "PROCEED WITH CAUTION": "CAUTION",
};
