export const MUSIC_PLAYLIST = [
  "/assets/audio/music/mesoelfy_os/01 - 004_16 - Aerlind (Cover) - Acid Techno, DnB, atmospheric pads.mp3",
  "/assets/audio/music/mesoelfy_os/02 - 002_14 - Dolen Angol (Cover) - cyberpunk, darksynth, psybient, chopped sample, glitch, chiptune, synth cadenza.mp3",
  "/assets/audio/music/mesoelfy_os/03 - Elf Girl 009 - ambient chiptune, jazz fusion, virtuosic harmonic melodic exploration.mp3",
  "/assets/audio/music/mesoelfy_os/04 - Elf Girl 009 - ambient chiptune, jazz fusion, virtuosic harmonic melodic exploration.mp3",
  "/assets/audio/music/mesoelfy_os/05 - 007_04 - Dant Arth (Cover) - dark chiptune, jazz fusion, virtuosic harmonic melodic exploration.mp3",
  "/assets/audio/music/mesoelfy_os/06 - Elf Girl 009 - ambient chiptune, jazz fusion, virtuosic harmonic melodic exploration.mp3",
  "/assets/audio/music/mesoelfy_os/07 - 003_24 - Lach Mí (Cover) - Acid Techno, DnB, atmospheric pads.mp3",
  "/assets/audio/music/mesoelfy_os/08 - 001_01 - Dúath Maethor (Cover) - psybience.mp3",
  "/assets/audio/music/mesoelfy_os/09 - 008_01 - Galu na Vëa (Cover) - dark chiptune, jazz fusion, virtuosic harmonic melodic exploration.mp3",
  "/assets/audio/music/mesoelfy_os/10 - Elf Girl 009 - chiptune, jazz fusion, cyberpunk, chopped sample, glitch, virtuosic harmonic melodic exploration.mp3",
  "/assets/audio/music/mesoelfy_os/11 - 007_01 - Angwedh Thinnas (Cover) - dark chiptune, jazz fusion, virtuosic harmonic melodic exploration.mp3",
  "/assets/audio/music/mesoelfy_os/12 - 004_01 - Tyaliéli Vendë (Cover) - chiptune, japanese funk, jazz fusion, virtuosic harmonic melodic exploration.mp3",
  "/assets/audio/music/mesoelfy_os/13 - 008_08 - Alcar mi Morë (Cover) - dark chiptune, jazz fusion, virtuosic harmonic melodic exploration.mp3",
  "/assets/audio/music/mesoelfy_os/14 - 008_13 - Fuin Roch (Cover) - chiptune, japanese funk, jazz fusion, virtuosic harmonic melodic exploration.mp3",
  "/assets/audio/music/mesoelfy_os/15 - 004_05 - Edraith o Rhach (Cover) - psybient.mp3",
  "/assets/audio/music/mesoelfy_os/16 - 006_22 - Míruvórë Silda (Cover) - dark chiptune, jazz fusion, virtuosic harmonic melodic exploration.mp3",
  "/assets/audio/music/mesoelfy_os/17 - Elf Girl 009 - ambient chiptune, jazz fusion, virtuosic harmonic melodic exploration.mp3",
  "/assets/audio/music/mesoelfy_os/18 - 006_10 - Nárë Inwisti (Cover) - dark chiptune, folktronica, virtuosic harmonic melodic exploration.mp3",
  "/assets/audio/music/mesoelfy_os/19 - 007_07 - Tuima Morë (Cover) - folktronica.mp3",
  "/assets/audio/music/mesoelfy_os/20 - 007_16 - Calu Am Calu (Cover) - chiptune, japanese funk, jazz fusion, virtuosic harmonic melodic exploration.mp3",
  "/assets/audio/music/mesoelfy_os/21 - 001_20 - Amrûn Echui (Cover).mp3",
  "/assets/audio/music/mesoelfy_os/22 - Elf Girl 009 - ambient chiptune, jazz fusion, virtuosic harmonic melodic exploration.mp3",
  "/assets/audio/music/mesoelfy_os/23 - Elf Girl 009 - chiptune, jazz fusion, cyberpunk, chopped sample, glitch, virtuosic harmonic melodic exploration.mp3",
  "/assets/audio/music/mesoelfy_os/24 - Elf Girl 009 - chiptune, jazz fusion, cyberpunk, chopped sample, glitch, virtuosic harmonic melodic exploration.mp3",
  "/assets/audio/music/mesoelfy_os/25 - Elf Girl 009 - ambient chiptune, jazz fusion, virtuosic harmonic melodic exploration.mp3"
];
