export const AI_CONFIG = {
  HUNTER: {
    ORBIT_SPEED: 0.5,
    TARGET_RADIUS: 10.0,
    AIM_LERP: 0.05,
    CHARGE_LERP: 0.15,
    SPIN_SPEED_IDLE: 2.0,
    SPIN_SPEED_CHARGE: -8.0,
    PROJECTILE_SPEED: 25,
    OFFSET_DIST: 1.6,
    RECOIL_FORCE: 2.0
  },
  KAMIKAZE: {
    ROTATION_SPEED: 10.0,
    ENGAGEMENT_DIST: 0.1
  },
  DRILLER: {
    SNAP_THRESHOLD: 0.1,
    TIP_OFFSET: 0.4, // Based on Model Height
    AUDIO_INTERVAL: 0.25
  },
  DAEMON: {
    SHIELD_CHARGE_TIME: 2.0,
    COOLDOWN_TIME: 0.5,
    RECOVERY_TIME: 2.0,
    ORBIT_RADIUS: 4.0,
    ORBIT_SPEED_MIN: 1.5,
    ROTATION_SPEED: {
      CHARGING: 15.0,
      READY: 3.0,
      FIRE: 20.0,
      COOLDOWN: -5.0,
      BROKEN: 30.0
    }
  }
};
