export const COLORS = {
  GREEN: '#78F654',
  YELLOW: '#F7D277',
  RED: '#FF003C',
  PURPLE: '#9E4EA5',
  BLACK: '#000000',
  WHITE: '#FFFFFF',
};

export const BOOT_KEYS: Record<string, string> = {
    "INITIALIZE NEURAL_LACE": "INIT",
    "CONNECTED TO LATENT_SPACE": "LINK",
    "MOUNT MESOELFY_CORE": "MOUNT",
    "UNSAFE CONNECTION DETECTED": "UNSAFE",
    "BYPASSING SENTINEL_NODES": "BYPASS",
    "DECRYPTED": "DECRYPTED",
    "PROCEED WITH CAUTION": "CAUTION",
};
